### ISSUE TITLE
Planes and shooting range

### ISSUE THREAD

**Issue by StrejdaJoe** [Piraj/Fatal-Puppies-Squad-BootCamp#12]
Hello, it's me again.

**Is your feature request related to a problem? Please describe.**
It has been reported to me that the airplanes located at an aircraft carrier require Jets DLC. Next thing is that the dueling target at shooting range is turned "backwards" to shooters.

**Describe the solution you'd like**
Could you please check if the planes really need the Jets DLC and if they do, could you please replace them with some that do not require so? And turn the dueling target around by 180 degrees.

Looking forward to your reply
UncleJoe

**Comment by Piraj** [comment]
The Black Wasp is the only actually carrier capable aircraft that is in the game, I can exchange some of them for unrealistic options but why not just use the island airport instead for A-10's etc.?

Dueling target rotation is already staged for the next version but not a priority since as far as I saw it is just a visual fix. Otherwise it works either way.
